### ISSUE TITLE
cmake requires FindGnuradio.cmake

### ISSUE THREAD

**Issue by kzembower** [balint256/gr-rds#3]
I'm very new to GNUradio and cmake, so this problem is probably an easy one.

When I get gr-rds and run cmake, I get:
.............................................................................
kevin@kevin-asrock:~/GNU_Radio/gr-rds/build$ cmake ..
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
CMake Warning at CMakeLists.txt:96 (find_package):
  By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Gnuradio",
  but CMake did not find one.

  Could not find a package configuration file provided by "Gnuradio" with any
  of the following names:

```
GnuradioConfig.cmake
gnuradio-config.cmake
```

  Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
  "Gnuradio_DIR" to a directory containing one of the above files.  If
  "Gnuradio" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at CMakeLists.txt:99 (message):
  GnuRadio Runtime required to compile gr-rds

-- Configuring incomplete, errors occurred!
See also "/home/kevin/GNU_Radio/gr-rds/build/CMakeFiles/CMakeOutput.log".
kevin@kevin-asrock:~/GNU_Radio/gr-rds/build$ 
.........................................................
I also tried 'cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..' and 'cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/share/gnuradio ..' as well as 'cmake -DCMAKE_PREFIX_PATH=/usr/share/gnuradio ..' without success.

I was unable to locate the GNUradio executable; don't know executable's name.

As I said, these are probably easy to fix, but I'm a newbie. Thanks for looking into these.

-Kevin

**Comment by bastibl** [comment]
Did you search for the files mentioned in the error message (GnuradioConfig.cmake)? Are they really located under /usr/share/gnuradio? For me it would be something like

```
cmake -DCMAKE_PREFIX_PATH=/usr/lib/cmake/gnuradio ..
```

What version of GNU Radio are you using and how did you install it?

**Comment by kzembower** [comment]
Hello, thanks for writing back. I really enjoyed your talks on YouTube.

Yes, I searched without success:
kevin@kevin-asrock:~$ find /usr/ -name GnuradioConfig.cmake
kevin@kevin-asrock:~$ 
kevin@kevin-asrock:~$ find /usr/ -name gnuradio-config.cmake
kevin@kevin-asrock:~$ 

I installed it via 'apt-get install' for my Ubuntu 14.01 system:
Start-Date: 2015-02-03  19:08:16
Commandline: aptdaemon role='role-commit-packages' sender=':1.135'
Install: libgl1-mesa-dev:amd64 (10.1.3-0ubuntu0.3, automatic), libboost-regex1.54.0:amd64 (1.54.0-4ubuntu3.1, automatic), libxshmfence-dev:amd64 (1.1-2, automatic), libglu1-mesa-dev:amd64 (9.0.0-2, automatic), libxxf86vm-dev:amd64 (1.1.3-1, automatic), qthid-fcd-controller:amd64 (4.1-3, automatic), libgnuradio-analog3.7.2.1:amd64 (3.7.2.1-5, automatic), ...

However, last night, I was trying to install gr-rds and used pybombs, which looks like it installed a complete new version of GNUradio, too. It looks like it installed gr-rds, but I haven't had a chance to check it out yet. Can you tell me how to run the version of GNUradio that pybombs might have installed?

Thanks so much for your work with GNUradio.

-Kevin

**Comment by bastibl** [comment]
I would remove the version from the repos since it's usually outdated (and two versions can cause very weird problems).
If you did not find the config file after you installed GNU Radio via pybombs, maybe you chose a different install prefix during installation (then you have to adapt the path accordingly). Once everything is installed properly you can open the rds_rx.grc flow graph in gnuradio-companion and run it. (again, where the flow graph is installed depends on your configuration).
Hope it helps,
Bastian

**Comment by kzembower** [comment]
Hi, Bastian, I decided not to follow your advice about removing the Ubuntu package and using pybombs. I tried to do this, but got immedate errors about python paths, that I didn't understand. In addition, the version in Ubuntu 14.04.2 is GNURadio 3.7.2.1, which is up-to-date enough for me.

I think the solution to my original problem is to run:
 sudo apt-get install gnuradio-dev

This seemed to make the problem go away, and I've now compiled and installed gr-rds without a problem. I'll let you know if I run into any more problems.

Thanks again, for your efforts to help me, and for your work on the GNURadio project.

-Kevin

**Comment by bastibl** [comment]
Hi Kevin,
great that it works for you! The point is that 3.7.2.1 over one year old and many modules don't work with that outdated version... so you might run into problems soon.
I never used pybombs but for me it sound like you did not create or source the environment file. See http://gnuradio.org/redmine/projects/pybombs/wiki/QuickStart
Whatever... since it works for you it would be great if you could close the issue.
Bastian

**Comment by kzembower** [comment]
Sorry. Didn't know I needed to close the issue. Thanks, again, for all your help. I didn't realize that 3.7.2.1 is a year old.

-Kevin
